name: 'set version'
inputs:
  version:
    type: string
    required: true
    default: "current"
    description: "Version which should be used. If 'current' is used the version in pubspec.yaml will be used."
  increase_build_number:
    type: boolean
    required: true
    description: "If true the buildnumber will be increased by one."
  tag_prefix:
    type: boolean
    requried: true
    description: "Prefix which should be used for the tag."

description: 'increases the buildnumber by one if increase_build_number and set the version in pubspec, pushes, and tag the changes'
runs:
  using: "composite"
  steps:
    - name: Extract version
      id: extract-version
      shell: bash
      env:
        FILE: "pubspec.yaml"
      run: |
        VERSION_VALUE=$(grep '^version:' "$FILE" | cut -d':' -f2 | tr -d ' ')
        VERSION="${VERSION_VALUE%%+*}"
        BUILD_NUMBER="${VERSION_VALUE##*+}"
        
        echo "CURRENT_VERSION=$VERSION" >> "$GITHUB_OUTPUT"
        echo "CURRENT_BUILD=$BUILD_NUMBER" >> "$GITHUB_OUTPUT"

    - name: Decide version bump
      id: bump
      shell: bash
      env:
        CURRENT_VALUE: "current"
        INPUT_VERSION: ${{ inputs.version }}
        CURRENT_VERSION: ${{ steps.extract-version.outputs.CURRENT_VERSION }}
        CURRENT_BUILD: ${{ steps.extract-version.outputs.CURRENT_BUILD }}
        INCREASE_BUILD_NUMBER: ${{ inputs.increase_build_number }}
      run: |                
        # Decide new version
        NEW_VERSION="$INPUT_VERSION"
        if [ "$INPUT_VERSION" = $CURRENT_VALUE ]; then
          NEW_VERSION="$CURRENT_VERSION"
        fi
        
        # Decide new build
        NEW_BUILD="$CURRENT_BUILD"
        if $INCREASE_BUILD_NUMBER; then
          NEW_BUILD=$((CURRENT_BUILD + 1))
        fi
        
        # Decide if anything changed
        if [ "$NEW_VERSION" != "$CURRENT_VERSION" ] || [ "$NEW_BUILD" != "$CURRENT_BUILD" ]; then
         SHOULD_CHANGE=true
        else
         SHOULD_CHANGE=false
        fi
                
        echo "NEW_VERSION=$NEW_VERSION" >> "$GITHUB_OUTPUT"
        echo "NEW_BUILD_NUMBER=$NEW_BUILD" >> "$GITHUB_OUTPUT"
        echo "SHOULD_CHANGE=$SHOULD_CHANGE" >> "$GITHUB_OUTPUT"

    - name: set version in pubspec and tag
      shell: bash
      if: ${{ steps.bump.outputs.SHOULD_CHANGE == 'true' }}
      env:
        FILE: "pubspec.yaml"
        VERSION: ${{ steps.bump.outputs.NEW_VERSION }}
        BUILD_NUMBER: ${{ steps.bump.outputs.NEW_BUILD }}
        TAG_PREFIX: ${{ inputs.tag_prefix }}
      run: |
        # Set new version in file
        sed -i -E "s/version: .*$/version: $VERSION+$BUILD_NUMBER/" $FILE
        
        git config --global user.name 'github action'
        git config --global user.email 'developer@hansefit.de'
        
        git commit -am "$VERSION $BUILD_NUMBER" || true
        git tag "$TAG_PREFIX-$VERSION($BUILD_NUMBER)"
        git push || true
