name: 'Build ios'
inputs:
  deploy:
    description: 'Defines if deploy action should take place'
    type: boolean
    required: true
  ENV:
    required: true
  DEV_ENV:
    description: 'Only used in deploy_dev fastlane script'
    default: "DEV"
  SOME_SECRET:
    required: true
  SOME_SECRET2:
    required: true

description: 'deploys the app to the appstore'
runs:
  using: "composite"
  steps:
    - env:
        SOME_SECRET: ${{ inputs.SOME_SECRET }}
        SOME_SECRET2: ${{ inputs.SOME_SECRET2 }}
      run: |
        echo "ENV ${{ inputs.ENV }}"
        echo "DEV_ENV ${{ inputs.DEV_ENV }}"
        if [[ -z "$SOME_SECRET" ]]; then
          echo "SOME_SECRET is empty"
        else 
          echo "SOME_SECRET is not empty"
        fi
        
        if [[ -z "$SOME_SECRET2" ]]; then
                  echo "SOME_SECRET2 is empty"
                else 
                  echo "SOME_SECRET2 is not empty"
                fi
      shell: bash
