name: Build Flavor

on:
  workflow_call:
    inputs:
      env:
        description: 'Environment. Must be: DEV, TEST, PROD'
        type: string
        required: true
      dev_override_env:
        description: 'Optional Environment override for the API keys when using the DEV flavor.'
        type: string
        required: false
        default: ''
      deploy:
        description: 'Defines if deploy action should take place'
        type: boolean
        required: true
      android:
        description: 'Should build Android'
        type: boolean
        required: true
        default: true
      ios:
        description: 'Should build iOS'
        type: boolean
        required: true
        default: true
      huawei:
        description: 'Should build Huawei'
        type: boolean
        required: true
        default: false

jobs:
  validate-inputs:
    runs-on: ubuntu-latest
    outputs:
      normalized_flavor: ${{ steps.validate_flavor.outputs.normalized_flavor }}
    steps:
      - uses: actions/checkout@v4

      - name: Validate flavor
        id: validate_flavor
        uses: ./.github/actions/validate_flavor/
        with:
          flavor: ${{ inputs.env }}

      - name: Validate override flavor
        id: validate_override_flavor
        if: ${{ inputs.dev_override_env != '' }}
        uses: ./.github/actions/validate_flavor/
        with:
          flavor: ${{ inputs.dev_override_env }}

  define_flavor_arguments:
    needs: validate-inputs
    runs-on: ubuntu-latest
    outputs:
      normalized_flavor: ${{ steps.set.outputs.normalized_flavor }}
      dev_override_flavor: ${{ steps.set.outputs.dev_override_flavor }}
      some_secret: ${{ steps.set.outputs.some_secret }}
    env:
      INPUT_FLAVOR: ${{ inputs.env }}
      DEV_OVERRIDE_FLAVOR: ${{ inputs.dev_override_env }}

      SECRET1: ${{ secrets.SECRET1 }}
      SECRET2: ${{ secrets.SECRET2 }}
    steps:
      - name: Set values
        id: set
        run: |
          API_FLAVOR=$INPUT_FLAVOR
          NORMALIZED_FLAVOR=${{ needs.validate-inputs.outputs.normalized_flavor }}
          


          
          # --- 4️⃣Export outputs ---
          {
            echo "normalized_flavor=$NORMALIZED_FLAVOR"
            echo "dev_override_flavor=$API_FLAVOR"
            echo "some_secret=${{ secrets.SECRET1 }}"
          } >> "$GITHUB_OUTPUT"

  build_ios:
    needs: define_flavor_arguments
    name: Build iOS
    runs-on: ubuntu-latest
    if: ${{ inputs.ios }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 2

      - name: build
        uses: ./.github/actions/build_ios/
        with:
          ENV: ${{ needs.define_flavor_arguments.outputs.normalized_flavor }}
          DEV_ENV: ${{ needs.define_flavor_arguments.outputs.dev_override_flavor }}
          SOME_SECRET: ${{ needs.define_flavor_arguments.outputs.some_secret }}
          SOME_SECRET2: ${{ secrets.SECRET2 }}
