name: Build dev

permissions: write-all

on:
  workflow_dispatch:

jobs:
  build_dev:
    needs: lint
    uses: ./.github/workflows/build_flavor.yaml
    secrets: inherit
    with:
      env: DEV
      deploy: false
      ios: true
      android: true
      huawei: false