name: Build Flavor

on:
  workflow_call:
    inputs:
      flavor:
        description: 'Environment. Must be: DEV, BETA, PROD'
        type: string
        required: true
      android:
        description: 'Should build Android'
        type: boolean
        required: true
        default: true
      ios:
        description: 'Should build iOS'
        type: boolean
        required: true
        default: true
      huawei:
        description: 'Should build Huawei'
        type: boolean
        required: true
        default: false

    outputs:
      android_result:
        description: "The result of the Android build job"
        value: ${{ jobs.android.result }}
      ios_result:
        description: "The result of the iOS build job"
        value: ${{ jobs.ios.result }}
      huawei_result:
        description: "The result of the Huawei build job"
        value: ${{ jobs.huawei.result }}

jobs:
  validate-inputs:
    name: Validate inputs
    runs-on: ubuntu-latest
    steps:
      - name: validate-inputs
        shell: bash
        run: |
          echo 'validate-inputs'
          sleep 3

  define-flavor-arguments:
    name: Define flavor arguments
    needs: validate-inputs
    runs-on: ubuntu-latest
    steps:
      - name: define-flavor-arguments
        shell: bash
        run: |
          echo 'define-flavor-arguments'
          sleep 2

  android:
    name: Build Android
    needs: define-flavor-arguments
    runs-on: ubuntu-latest
    if: ${{ inputs.android }}
    steps:
      - name: Build android
        id: build_android
        shell: bash
        run: |
          echo 'Build android'
          sleep 10

  huawei:
    name: Build huawei
    needs: define-flavor-arguments
    runs-on: ubuntu-latest
    timeout-minutes: 40
    if: ${{ inputs.huawei }}
    steps:
      - name: Build huawei
        id: build_huawei
        shell: bash
        run: |
          echo 'Build huawei'
          sleep 10

  ios:
    name: Build iOS
    needs: define-flavor-arguments
    runs-on: macOS-15
    timeout-minutes: 30
    if: ${{ inputs.ios }}
    steps:
      - name: Build iOS
        id: build_ios
        shell: bash
        run: |
          echo 'Build iOS'
          sleep 10
