name: Build dev

permissions: write-all

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        options:
          - DEV
          - BETA
          - PROD
jobs:
  build_dev:
    uses: ./.github/workflows/build_flavor.yaml
    secrets: inherit
    with:
      env: ${{ github.event.inputs.env }}
      deploy: false
      ios: true
      android: true
      huawei: false