name: Check

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: version for store
        required: true
      increase_build_number:
        type: string
        description: increase the build number
        required: true

jobs:
  set-version:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/set_version/
        with:
          version: ${{ inputs.version }}
          increase_build_number: ${{ inputs.increase_build_number }}
          tag_prefix: dev