
on:
  workflow_dispatch:
    inputs:
      testing: 
        type: boolean

jobs:
  collect-changelog:
    if: ${{ github.event.inputs.testing == true }}
    name: Collect changelog
    runs-on: ubuntu-latest
    outputs:
      changelog_md: ${{ steps.generate.outputs.markdown }}
    steps:
      - uses: actions/checkout@v5

      - name: Generate changelog
        id: generate
        run: |
          scripts/changelog/generate_changelog.sh \
            --flavor "BETA" \
            --version "1.0.0" \
            --build "1" \
            --jira-url "https://hansefit.atlassian.net" \
            --jira-project "MAPP" \
            --output changelog.md

      - name: Upload changelog artifact
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: changelog.md
  
  notify-build-finish:
    name: Send Final Ping
    runs-on: ubuntu-latest
    needs: [ collect-changelog ]
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/notify_build_finish/
        with:
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack_channel_id: ${{ secrets.SLACK_BUILDS_CHANNEL_ID }}
