name: Test workflow

on:
  workflow_dispatch:
    inputs:
      ios:
        type: boolean
        required: true
        default: true
      android:
        type: boolean
        required: true
        default: true

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: test
        shell: bash
        run: |
          echo 'first'

  test:
    needs: first
    uses: ./.github/workflows/test_work_call.yaml
    with:
      ios: ${{ inputs.ios }}
      android: ${{ inputs.android }}