name: Test workflow on call

on:
  workflow_dispatch:
    inputs:
      success:
        type: boolean
        required: true
        default: true

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ inputs.success == 'true' }}
    steps:
      - shell: bash
        run: |
          echo "first job"
          sleep 20

  test2:
    needs: [ test ]
    runs-on: ubuntu-latest
    if: cancelled() && needs.test.result == 'success'
    steps:
      - shell: bash
        run: |
          echo "SECOND job"
