name: Test workflow

on:
  workflow_dispatch:
    inputs:
      ios:
        type: boolean
      android:
        type: boolean

jobs:
  test:
    uses: ./.github/workflows/test_work_call.yaml
    with:
      ios: ${{ inputs.ios }}
      android: ${{ inputs.android }}