name: Test workflow

on:
  workflow_dispatch:

jobs:
  define_arguments:
    runs-on: ubuntu-latest
    outputs:
      some_key_one: ${{ steps.set.outputs.some_key_one }}
      some_key_two: ${{ steps.set.outputs.some_key_two }}
    steps:
      - id: set
        run: |
          SOME_KEY_ONE="SOME KEY 1!!!!"
          SOME_KEY_TWO="SOME KEY 2@@@@"
          
          {
            echo "some_key_one=SOME_KEY_ONE"
            echo "some_key_two=SOME_KEY_TWO"
          } >> "$GITHUB_OUTPUT"

  echo_jon:
    needs: define_arguments
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "ONE: ${ steps.define_arguments.outputs.some_key_one }"
          echo "TWO: ${ steps.define_arguments.outputs.some_key_two }"