on:
  workflow_dispatch:
    inputs:
      ios:
        type: boolean
      android:
        type: boolean
      web:
        type: boolean
jobs:
  validate-inputs:
    runs-on: ubuntu-latest
    env:
      platforms_build: "${{ inputs.android }} ${{ inputs.ios }} ${{ inputs.web }}"
    steps:
      - name: Fail if none are true
        run: |
          [[ "$platforms_build" == *true* ]] || {
            echo "❌ No platform is true"
            exit 1
          }