on:
  workflow_dispatch:
    inputs:
      ios:
        type: boolean
      android:
        type: boolean
      web:
        type: boolean
jobs:
  validate-inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate
        uses: ./.github/actions/validate_deploy_targets/
        with:
          targets: "${{ inputs.android }} ${{ inputs.ios }} ${{ inputs.web }}"