on:
  workflow_dispatch:
    inputs:
      ios:
        type: boolean
      android:
        type: boolean
      web:
        type: boolean
jobs:
  validate-inputs:
    uses: ./.github/actions/validate_deploy_targets/
    with:
      targets: "${{ inputs.android }} ${{ inputs.ios }} ${{ inputs.web }}"